In [4]:
# Imports

import numpy as np
import pandas as pd
import json
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

In [6]:
# Importing and defining data

file_path1 = "D:/anaconda/yelp_regression_project/yelp_data.json"
file_path2 = "D:/anaconda/yelp_regression_project/yelp_business.json"
file_path3 = "D:/anaconda/yelp_regression_project/yelp_review.json"
file_path4 = "D:/anaconda/yelp_regression_project/yelp_checkin.json"
file_path5 = "D:/anaconda/yelp_regression_project/yelp_tip.json"
file_path6 = "D:/anaconda/yelp_regression_project/yelp_user.json"
file_path7 = "D:/anaconda/yelp_regression_project/yelp_photo.json"
yelp_data = pd.read_json(file_path1, lines=True)
yelp_business = pd.read_json(file_path2, lines=True)
yelp_review = pd.read_json(file_path3, lines=True)
yelp_checkin = pd.read_json(file_path4, lines=True)
yelp_tip = pd.read_json(file_path5, lines=True)
yelp_user = pd.read_json(file_path6, lines=True)
yelp_photo = pd.read_json(file_path7, lines=True)

In [353]:
# Defining X and y

x = pd.concat([yelp_data, yelp_business, yelp_review, yelp_checkin, yelp_tip, yelp_user, yelp_photo], axis = 1)
X = x.head(1000)

stars = X[['stars']]
y = stars.head(1000)

print(X.columns.tolist())

['address', 'attributes', 'business_id', 'categories', 'city', 'hours', 'is_open', 'latitude', 'longitude', 'name', 'neighborhood', 'postal_code', 'review_count', 'stars', 'state', 'alcohol?', 'has_bike_parking', 'takes_credit_cards', 'good_for_kids', 'price_range', 'take_reservations', 'has_wifi', 'pic_count', 'address', 'alcohol?', 'attributes', 'business_id', 'categories', 'city', 'good_for_kids', 'has_bike_parking', 'has_wifi', 'hours', 'is_open', 'latitude', 'longitude', 'name', 'neighborhood', 'postal_code', 'price_range', 'review_count', 'stars', 'state', 'take_reservations', 'takes_credit_cards', 'business_id', 'average_review_age', 'average_review_length', 'average_review_sentiment', 'number_funny_votes', 'number_cool_votes', 'number_useful_votes', 'business_id', 'time', 'weekday_checkins', 'weekend_checkins', 'business_id', 'average_tip_length', 'number_tips', 'business_id', 'average_number_friends', 'average_days_on_yelp', 'average_number_fans', 'average_review_count', 'aver

In [357]:
# Cleaning data

X = X.copy()
X_data.replace({True: 1, False: 0})

# Separate data sets

X_data = X.iloc[:, 0:23]
X_review = X.iloc[:, 46:52]
X_checkin = X.iloc[:, 53:56]
X_tip = X.iloc[:, 57:59]
X_user = X.iloc[:, 60:65]
X_photo = X.iloc[:, 66:68]

# Put irrelevant data at the start for deletion

X_data = X_data[['address', 'attributes', 'business_id', 'categories', 'city', 'name', 'postal_code', 'neighborhood', 'price_range', 'state', 'business_id', 'hours', 'stars', 'alcohol?', 'good_for_kids', 'has_bike_parking', 'has_wifi', 'is_open', 'latitude', 'longitude', 'review_count', 'take_reservations', 'takes_credit_cards']]

# Delete irrelevant (worded) data + stars

X_data = X_data.iloc[:, 13:23]
X_checkin = X_checkin.iloc[:, 1:3]


print(X_data.columns.tolist())
print(X_review.columns.tolist())
print(X_checkin.columns.tolist())
print(X_tip.columns.tolist())
print(X_user.columns.tolist())
print(X_photo.columns.tolist())

['alcohol?', 'good_for_kids', 'has_bike_parking', 'has_wifi', 'is_open', 'latitude', 'longitude', 'review_count', 'take_reservations', 'takes_credit_cards']
['average_review_age', 'average_review_length', 'average_review_sentiment', 'number_funny_votes', 'number_cool_votes', 'number_useful_votes']
['weekday_checkins', 'weekend_checkins']
['average_tip_length', 'number_tips']
['average_number_friends', 'average_days_on_yelp', 'average_number_fans', 'average_review_count', 'average_number_years_elite']
['average_caption_length', 'number_pics']


In [359]:
# Linear regression

X_data_train, X_data_test, y_data_train, y_data_test = train_test_split(X_data, y, test_size = 0.2, random_state = 42)
X_review_train, X_review_test, y_review_train, y_review_test = train_test_split(X_review, y, test_size = 0.2, random_state = 42)
X_checkin_train, X_checkin_test, y_checkin_train, y_checkin_test = train_test_split(X_checkin, y, test_size = 0.2, random_state = 42)
X_tip_train, X_tip_test, y_tip_train, y_tip_test = train_test_split(X_tip, y, test_size = 0.2, random_state = 42)
X_user_train, X_user_test, y_user_train, y_user_test = train_test_split(X_user, y, test_size = 0.2, random_state = 42)
X_photo_train, X_photo_test, y_photo_train, y_photo_test = train_test_split(X_photo, y, test_size = 0.2, random_state = 42)

lrg_data = LinearRegression().fit(X_data_train, y_data_train)
lrg_review = LinearRegression().fit(X_review_train, y_review_train)
lrg_checkin = LinearRegression().fit(X_checkin_train, y_checkin_train)
lrg_tip = LinearRegression().fit(X_tip_train, y_tip_train)
lrg_user = LinearRegression().fit(X_user_train, y_user_train)
lrg_photo = LinearRegression().fit(X_photo_train, y_photo_train)

y_data_test_pred = lrg_data.predict(X_data_test)
y_review_test_pred = lrg_review.predict(X_review_test)
y_checkin_test_pred = lrg_checkin.predict(X_checkin_test)
y_tip_test_pred = lrg_tip.predict(X_tip_test)
y_user_test_pred = lrg_user.predict(X_user_test)
y_photo_test_pred = lrg_photo.predict(X_photo_test)

print(lrg_data.coef_)
print(lrg_review.coef_)
print(lrg_checkin.coef_)
print(lrg_tip.coef_)
print(lrg_user.coef_)
print(lrg_photo.coef_)

[[-0.29035001 -0.14910713  0.27285689 -0.12187964 -0.02092519 -0.00748512
  -0.00193574  0.00069156  0.27065041  0.02379782]
 [-0.29035001 -0.14910713  0.27285689 -0.12187964 -0.02092519 -0.00748512
  -0.00193574  0.00069156  0.27065041  0.02379782]]
[[6.37815062e-05 1.25348704e-04 3.57424150e-02 9.31906374e-05
  2.76904171e-04 4.01389018e-05]
 [6.37815062e-05 1.25348704e-04 3.57424150e-02 9.31906374e-05
  2.76904171e-04 4.01389018e-05]]
[[-0.00079578  0.00110114]
 [-0.00079578  0.00110114]]
[[ 0.00028828 -0.00217958]
 [ 0.00028828 -0.00217958]]
[[ 5.87431665e-04  1.86655675e-04 -4.41502930e-03 -7.70740089e-05
  -4.34873409e-02]
 [ 5.87431665e-04  1.86655675e-04 -4.41502930e-03 -7.70740089e-05
  -4.34873409e-02]]
[[ 0.00114968 -0.00297282]
 [ 0.00114968 -0.00297282]]


In [363]:
# Evaluating model with R-Squared value

# Calculate and print R^2 scores for all datasets
data_r_squared_test = r2_score(y_data_test, y_data_test_pred)
print("R^2 score for data test set:", data_r_squared_test)

review_r_squared_test = r2_score(y_review_test, y_review_test_pred)
print("R^2 score for review test set:", review_r_squared_test)

checkin_r_squared_test = r2_score(y_checkin_test, y_checkin_test_pred)
print("R^2 score for checkin test set:", checkin_r_squared_test)

tip_r_squared_test = r2_score(y_tip_test, y_tip_test_pred)
print("R^2 score for tip test set:", tip_r_squared_test)

user_r_squared_test = r2_score(y_user_test, y_user_test_pred)
print("R^2 score for user test set:", user_r_squared_test)

photo_r_squared_test = r2_score(y_photo_test, y_photo_test_pred)
print("R^2 score for photo test set:", photo_r_squared_test)

R^2 score for data test set: -0.011957550208676615
R^2 score for review test set: -0.018178350197702864
R^2 score for checkin test set: -0.018626670979434046
R^2 score for tip test set: -0.004113833804468836
R^2 score for user test set: -0.06681411826262917
R^2 score for photo test set: -0.01929742333619533


In [ ]:
# These results show that no group of this data is significantly correlated with the number of stars for a restaurant.
# The model could be improved by incorporating lost data like 'hours'.
## To fix: could try using a different parameter than 'stars' (change y formula and reinsert 'stars' into data set)